### ISSUE TITLE
Initial Backend File Structure Setup #Medium 

### ISSUE THREAD

**Issue by srujanGowda08** [srujanGowda08/GroceryShare#2]
### 📋 Issue Description
Set up a scalable and maintainable file structure for the GroceryShare backend using Node.js, Express, and MongoDB.

### 🎯 Objectives
Create the following directory structure within the `server` folder:

```
server/
├── src/
│   ├── config/
│   │   ├── database.js
│   │   ├── socket.js
│   │   └── environment.js
│   ├── models/
│   │   ├── User.js
│   │   ├── List.js
│   │   ├── Recipe.js
│   │   └── Item.js
│   ├── controllers/
│   │   ├── auth/
│   │   │   ├── login.js
│   │   │   ├── register.js
│   │   │   └── index.js
│   │   ├── lists/
│   │   │   ├── create.js
│   │   │   ├── update.js
│   │   │   ├── delete.js
│   │   │   └── index.js
│   │   └── recipes/
│   │       ├── generate.js
│   │       ├── save.js
│   │       └── index.js
│   ├── routes/
│   │   ├── auth.routes.js
│   │   ├── list.routes.js
│   │   └── recipe.routes.js
│   ├── middleware/
│   │   ├── auth.middleware.js
│   │   ├── error.middleware.js
│   │   └── validation.middleware.js
│   ├── services/
│   │   ├── auth.service.js
│   │   ├── list.service.js
│   │   ├── recipe.service.js
│   │   └── ai.service.js
│   ├── utils/
│   │   ├── jwt.js
│   │   ├── logger.js
│   │   └── responses.js
│   └── validations/
│       ├── auth.validation.js
│       ├── list.validation.js
│       └── recipe.validation.js
├── tests/
│   ├── integration/
│   │   ├── auth.test.js
│   │   ├── list.test.js
│   │   └── recipe.test.js
│   └── unit/
│       ├── services/
│       └── utils/
├── logs/
├── .env.example
├── .gitignore
├── package.json
└── server.js
```

### 📝 Tasks
1. Initialize project and basic configuration:
   - [ ] Set up Node.js project with npm
   - [ ] Install essential dependencies
   - [ ] Configure environment variables
   - [ ] Set up MongoDB connection

2. Create core files:
   - [ ] Set up basic Express server
   - [ ] Create database configuration
   - [ ] Implement basic middleware
   - [ ] Set up error handling

3. Implement basic models:
   - [ ] Create User model
   - [ ] Create List model
   - [ ] Create Recipe model
   - [ ] Create Item model

4. Set up authentication:
   - [ ] Implement JWT utilities
   - [ ] Create auth middleware
   - [ ] Set up basic auth routes

### 🔧 Technical Requirements
```javascript
// Essential dependencies to install:
{
  "dependencies": {
    "express": "^4.18.2",
    "mongoose": "^7.0.0",
    "dotenv": "^16.0.3",
    "jsonwebtoken": "^9.0.0",
    "bcryptjs": "^2.4.3",
    "cors": "^2.8.5",
    "socket.io": "^4.6.1",
    "express-validator": "^7.0.1",
    "winston": "^3.8.2"
  },
  "devDependencies": {
    "jest": "^29.5.0",
    "supertest": "^6.3.3",
    "nodemon": "^2.0.22"
  }
}
```

### 📚 API Structure
Basic API endpoints to implement:

```
AUTH ROUTES
POST /api/auth/register
POST /api/auth/login
GET /api/auth/profile

LIST ROUTES
GET /api/lists
POST /api/lists
GET /api/lists/:id
PUT /api/lists/:id
DELETE /api/lists/:id

RECIPE ROUTES
GET /api/recipes
POST /api/recipes/generate
GET /api/recipes/:id
```

### 🔒 Security Requirements
- Implement JWT authentication
- Hash passwords using bcrypt
- Set up CORS configuration
- Implement rate limiting
- Add request validation

### 📊 Database Schema Examples
Basic User Schema:
```javascript
{
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  name: { type: String, required: true },
  lists: [{ type: mongoose.Schema.Types.ObjectId, ref: 'List' }],
  createdAt: { type: Date, default: Date.now }
}
```

Basic List Schema:
```javascript
{
  name: { type: String, required: true },
  owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  shared: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  items: [{
    name: String,
    quantity: Number,
    purchased: Boolean
  }],
  createdAt: { type: Date, default: Date.now }
}
```

### 🧪 Testing Requirements
- Set up Jest for testing
- Create unit tests for utilities
- Implement integration tests for APIs
- Achieve minimum 80% code coverage

### 📋 Definition of Done
- [ ] All directories and files created
- [ ] Basic server running
- [ ] MongoDB connection established
- [ ] Authentication system working
- [ ] Basic CRUD operations for lists
- [ ] Tests passing
- [ ] API documentation created
- [ ] Error handling implemented
- [ ] Logging system configured

### 💡 Additional Notes
- Follow RESTful API best practices
- Implement proper error handling
- Use async/await for asynchronous operations
- Include detailed comments for complex logic
- Set up proper logging system

**Comment by srujanGowda08** [comment]
@completed initial files with simple code
